services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
